version: '3.3'
services:

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
    # Передаем доп параметры вкомандной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net

  mongodb-exporter:
    image: ${USER_NAME}/mongodb-exporter
    environment:
      MONGODB_URI: mongodb://post_db:27017
    networks:
      - back_net

  post_db:
#    env_file: .env
    image: mongo:${MONGODB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
#    env_file: .env
#    build: ./ui
#    image: ${USER_NAME}/ui:${UI_VERSION}
    image: ${USER_NAME}/ui
    ports:
      - ${UI_HOST_PORT}:${UI_CONTAINER_PORT}/tcp
    networks:
      - front_net

  post:
#    env_file: .env
#    build: ./post-py
#    image: ${USER_NAME}/post:${POST_VERSION}
    image: ${USER_NAME}/post
    networks:
      - front_net
      - back_net

  comment:
#    env_file: .env
#    build: ./comment
#    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    image: ${USER_NAME}/comment
    networks:
      - front_net
      - back_net

volumes:

  post_db:
  prometheus_data:

networks:

  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${FRONT_NET_SUBNET}

  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${BACK_NET_SUBNET}
